package org.dits.proj1;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(b6369cce35e8b9c872bd9491ceae2e41)
 */
@org.kie.api.definition.type.Label(value = "Test Result")
public class TestResult extends java.lang.Object implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Certfied Date")
    @org.kie.api.definition.type.Position(value = 5)
    private java.util.Date certDate;
    
    @org.kie.api.definition.type.Label(value = "Patient ID")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.Long patientId;
    
    @org.kie.api.definition.type.Position(value = 6)
    private int priority;
    
    @org.kie.api.definition.type.Label(value = "Source")
    @org.kie.api.definition.type.Position(value = 4)
    private java.lang.String source;
    
    @org.kie.api.definition.type.Label(value = "System")
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.String system;
    
    @org.kie.api.definition.type.Label(value = "Test Name")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String testName;
    
    @org.kie.api.definition.type.Label(value = "Test Score")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.Double testScore;

    public TestResult() {
    }

    public TestResult(java.lang.Long patientId, java.lang.String testName, java.lang.Double testScore, java.lang.String system, java.lang.String source, java.util.Date certDate, int priority) {
        this.patientId = patientId;
        this.testName = testName;
        this.testScore = testScore;
        this.system = system;
        this.source = source;
        this.certDate = certDate;
        this.priority = priority;
    }


    
    public java.util.Date getCertDate() {
        return this.certDate;
    }

    public void setCertDate(java.util.Date certDate) {
        this.certDate = certDate;
    }
    
    public java.lang.Long getPatientId() {
        return this.patientId;
    }

    public void setPatientId(java.lang.Long patientId) {
        this.patientId = patientId;
    }
    
    public int getPriority() {
        return this.priority;
    }

    public void setPriority(int priority) {
        this.priority = priority;
    }
    
    public java.lang.String getSource() {
        return this.source;
    }

    public void setSource(java.lang.String source) {
        this.source = source;
    }
    
    public java.lang.String getSystem() {
        return this.system;
    }

    public void setSystem(java.lang.String system) {
        this.system = system;
    }
    
    public java.lang.String getTestName() {
        return this.testName;
    }

    public void setTestName(java.lang.String testName) {
        this.testName = testName;
    }
    
    public java.lang.Double getTestScore() {
        return this.testScore;
    }

    public void setTestScore(java.lang.Double testScore) {
        this.testScore = testScore;
    }
}